/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
  // Apply the java-library plugin for API and implementation separation.
  `java-library`
  id("com.github.johnrengelman.shadow") version "5.1.0"
}

repositories {
  // Use JCenter for resolving dependencies.
  jcenter()
}

dependencies {
  // Use JUnit test framework.
  // testImplementation("junit:junit:4.13")

  // This dependency is exported to consumers, that is to say found on their compile classpath.
  // api("org.apache.commons:commons-math3:3.6.1")

  // These dependencies are used internally, and not exposed to consumers on their own compile classpath.
  implementation("org.eclipse.jetty.aggregate:jetty-all:9.0.0.RC2")
  implementation(files("src/main/resources/jade-4.5.0.jar"))
}

tasks {
  withType<ShadowJar> {
    archiveClassifier.set("")
    manifest {
      attributes(mapOf("Implementation-Title" to "org_hyperagents_jade_HypermediaAgentSystem"))
    }
  }
}
